/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "🎮 Game Version:": "🎮 游戏版本:",
    "HP": "生命值",
    "Epic": "史诗",
    "CRIT:": "暴击:",
    "CRIT DMG:": "暴击伤害:",
    "Chest:": "胸甲:",
    "HP REGEN:": "生命值回复:",
    "Belt:": "腰带:",
    "Boots:": "靴子:",
    "ATK:": "攻击:",
    "ATK SPD:": "攻击速度:",
    "Cooldown:": "冷却:",
    "Floor:": "层数:",
    "Gloves:": "手套:",
    "Weapon:": "武器:",
    "Helmet:": "头盔:",
    "Rogue:": "刺客:",
    "Everfall:": "永恒陨落:",
    "Paladin:": "圣骑士:",
    "Start Floor:": "开始层数:",
    "Tank:": "坦克:",
    "Archer:": "射手:",
    "Healer:": "治疗师:",
    "Mage:": "法师:",
    "Amulet:": "护身符:",
    "CDR:": "CDR:",
    "Chests Found:": "发现的宝箱:",
    "DODGE:": "闪避:",
    "Gold Earned:": "赚取金币:",
    "Deaths:": "死亡:",
    "DEF:": "防御:",
    "Min Item Level:": "最低物品等级:",
    "Mana Cost:": "法力成本:",
    "MANA REGEN:": "法力回复:",
    "Empty": "空",
    "(scales": "(缩放",
    "⸸️ Pause": "⸸️ 暂停",
    "Exit Game?": "退出游戏?",
    "Combat Log": "战斗日志",
    "Collapse All": "全部收起",
    "Common": "普通",
    "Defense": "防御",
    "Continue": "继续",
    "Controls": "控制",
    "Current Run": "当前运行",
    "CHESTS": "宝箱",
    "Everfall": "永恒陨落",
    "Everfall - Floor 1 - Chamber": "永恒陨落 - 层数 1 - 密室",
    "Everfall - Floor 1 - Entrance": "永恒陨落 - 层数 1 - 入口",
    "Everfall - Floor 1 - Fountain of Youth": "永恒陨落 - 层数 1 - 青春之泉",
    "MYTHIC": "神话",
    "Mana": "法力",
    "PET": "宠物",
    "RUNE": "符文",
    "Rogue": "刺客",
    "Rare": "稀有",
    "Popups": "弹出框",
    "STATS": "属性",
    "Stats": "属性",
    "LEVEL": "等级",
    "RARITY": "稀有度",
    "Tank": "坦克",
    "Tank • Frontline": "坦克 • 前线",
    "VICTORY": "胜利",
    "! Works on all rarities, including": "! 适用于所有稀有度，包括",
    "• Divine Arena Kills": "• 神圣竞技场击杀",
    "• First submission: 2 minutes after game start": "• 首次提交：游戏开始后2分钟",
    "• Highest Floor Reached": "• 达到的最高层数",
    "• Highest Gear Score": "• 最高装备积分",
    "• Most Mythics Found": "• 最多神话发现",
    "• Most Pets Found": "• 最多宠物发现",
    "• Rune Trial Boss Kills": "• 符文试炼Boss击杀数",
    "• Then every 30 minutes automatically": "• 然后每30分钟自动一次",
    "• Vault Boss Kills": "• 金库Boss击杀",
    "⚔️ Damage Dealt": "⚔️ 造成伤害",
    "⚔️ Everfall": "⚔️ 永恒陨落",
    "⚡ BLESSING POWER:": "⚡ 祝福之力：",
    "⚡ Ultra Endgame - Infinite Floors - Earn Blessing Currency ⚡": "⚡ 终极终局-无限楼层-赚取祝福货币⚡",
    "✨ Blessing Currency": "✨ 祝福货币",
    "✨ Divine Arena ✨": "✨ 神圣竞技场 ✨",
    "🌑 Umbral Depths": "🌑 阴暗的深处",
    "🎯 Floor Selection:": "🎯 楼层选择：",
    "🏆 VIEW LEADERBOARD": "🏆 查看排行榜",
    "📊 Stats": "📊 统计数据",
    "📊 View Drop Table": "📊 查看掉落表",
    "🔄 RESET ACCOUNT": "🔄 重置帐户",
    "🔄 Reset Account & Start Fresh": "🔄 重置帐户并重新开始",
    "🔒 Vault": "🔒 金库",
    "🔥 Stoneforge": "🔥 石炉",
    "🔮 Rune Trial": "🔮 符文试炼",
    "🛑 End Run": "🛑 结束运行",
    "1. Divine Shield": "1. 圣盾术",
    "1. Fireball": "1. 火球",
    "1. Heal": "1. 治疗",
    "1. Multi-Shot": "1. 多重射击",
    "10% drop chance per floor (10% are Mythic)": "每层10%掉落几率（10% 神话）",
    "10% drop chance per floor cleared": "每清除一层有 10% 掉落几率",
    "15% of their max HP": "最大生命的 15%",
    "2. No Keystone Equipped": "2. 未配置钥匙石",
    "5% of target max HP + (Bonus Mana × 0.4) + 10 flat": "5% 的目标最大生命值 +（额外法力值 × 0.4） + 10浮动",
    "A deadly assassin who strikes with precision, dealing massive burst damage from the shadows.": "一个致命的刺客，精准打击，从阴影中造成巨大的爆发伤害。",
    "A divine caster who keeps allies alive with powerful restoration magic and blessings.": "一个神圣的施法者，用强大的恢复魔法和祝福维持盟友的生命。",
    "A holy warrior who shields allies with divine blessings and smites enemies with righteous fury.": "一个神圣的战士，用神圣的祝福保护盟友，用正义的愤怒打击敌人。",
    "A master of arcane arts who unleashes devastating spells from afar with explosive power.": "奥术大师，能从远处释放具有爆炸威力的毁灭性法术。",
    "A nimble marksman who rains arrows on enemies with deadly accuracy and rapid fire.": "敏捷的射手，以致命的精确度和快速的射击射向敌人。",
    "A stalwart defender who protects allies with unbreakable resolve and powerful taunts.": "一个坚强的守卫者，用坚不可摧的决心和强大的嘲讽来保护盟友。",
    "ABILITIES": "能力",
    "and choose \"Bless Item\" to enhance it here": "并选择\“祝福物品\”来增强它",
    "and permanently enhances an item with powerful bonuses.": "并永久强化某件物品，获得强力加成。",
    "Archer": "射手",
    "at enemies, each dealing": "攻击敌人，每次造成",
    "Attack": "攻击",
    "attack damage (scales": "攻击伤害（缩放）",
    "attack damage each (AOE) (scales": "每次攻击伤害（AOE）（缩放）",
    "Auto-Submit Timer": "自动提交定时器",
    "Blasts all enemies for": "攻击所有敌人造成",
    "Bless Items": "祝福物品",
    "Blessing Currency equal to the item's level": "祝福货币等于物品的等级",
    "BUILD YOUR PARTY": "组建你的队伍",
    "Cache": "物资",
    "Choose any starting floor from 1-50 for each dungeon. Pick your preferred challenge level and jump right into the action! Your best floor reached is tracked for each dungeon.": "为每个地下城选择1-50的起始楼层。选择你喜欢的挑战级别，并直接进入行动！每个地下城都会追踪你到达的最佳楼层。",
    "Click on any equipped item on your characters": "点击角色身上的任何装备",
    "Divine Arena": "神圣竞技场",
    "DPS • Assassin": "DPS•刺客",
    "DPS • Caster": "DPS•施法者",
    "DPS • Ranged": "DPS•远程",
    "Drops: Amulets, Rings": "掉落物：护身符，戒指",
    "Drops: Chests, Helmets, Gloves, Belts, Boots": "掉落：箱子，头盔，手套，腰带，靴子",
    "Drops: Weapons": "掉落：武器",
    "Dungeon Progress": "地下城进度",
    "Dungeon:": "地下城：",
    "dungeon. Each blessing costs": "地下城。每次祝福消耗",
    "Earned from the": "赚取自",
    "Elite Boss - Hard (Requires Rune Trial Key) - Earn Runes": "精英Boss -困难（需要符文试炼钥匙）-获得符文",
    "Elite Boss - Hard (Requires Vault Key) - Earn Keystones": "精英Boss -困难（需要金库钥匙） -获得钥匙石",
    "Enemies Defeated:": "击败敌人:",
    "Equip a Archer Keystone from the Keystones tab to unlock a powerful second ability": "从“钥匙石”选项卡中装备一个射手钥匙石来解锁一个强大的第二技能",
    "Equip a Healer Keystone from the Keystones tab to unlock a powerful second ability": "从“钥匙石”选项卡中装备一个治疗师钥匙石来解锁一个强大的第二技能",
    "Equip a Mage Keystone from the Keystones tab to unlock a powerful second ability": "从“钥匙石”选项卡中装备一个法师钥匙石来解锁一个强大的第二技能",
    "Equip a Paladin Keystone from the Keystones tab to unlock a powerful second ability": "从“钥匙石”选项卡装备一个圣骑士钥匙石来解锁强大的第二技能",
    "Equipped Keystones": "已装备的钥匙石",
    "Equipped Runes (5 Slots)": "装备符文（5个槽位）",
    "Fallen Scout": "陨落的侦察兵",
    "Farthest Floor:": "最远楼层：",
    "Fastest Floor:": "最快楼层：",
    "Fires": "火",
    "Floor Completed:": "完成楼层：",
    "Floors Cleared:": "清理楼层：",
    "for": "用于",
    "FOUNTAIN OF YOUTH": "青春之泉",
    "Fountain of Youth! Party is recovering...": "青春之泉！队伍正在恢复中……",
    "Fullscreen Mode": "全屏模式",
    "Game saved": "游戏保存",
    "GEAR": "装备",
    "Grants all allies a shield equal to": "给予所有盟友一个相等的护盾",
    "Healer": "治疗师",
    "Heals an injured ally for": "治疗一个受伤的队友",
    "Hollow Stag": "空心雄鹿",
    "HP (scales": "生命值 (缩放",
    "Increases": "增加",
    "INVENTORY": "库存",
    "Items": "物品",
    "Items below this level will auto-sell": "低于这个等级的物品将自动出售",
    "items": "物品",
    "Keys drop from floor 45+ (2% chance)": "钥匙从45层掉落+（2%几率）",
    "Keystone Inventory": "钥匙石库存",
    "Keystones": "钥匙石",
    "KEYSTONES": "钥匙石",
    "Leaderboard": "排行榜",
    "Legendaries Found:": "发现的传说：",
    "Legendary": "传说",
    "LIFESTEAL:": "吸血：",
    "LOOT": "战利品",
    "Loot Filter - Level": "战利品过滤器-等级",
    "Loot Filter - Rarity": "战利品过滤器-稀有度",
    "Loot Obtained:": "获得的战利品：",
    "Mage": "法师",
    "casts Fireball": "施放火球",
    "Mirror": "镜像",
    "No Chests": "暂无宝箱",
    "No pet equipped": "暂未装备宠物",
    "No Rune Trial Keys": "没有符文试炼钥匙",
    "No stats yet": "没有统计数据",
    "No Vault Keys": "没有金库钥匙",
    "Off-Tank • Support": "副 - 坦克·辅助",
    "on your item by": "在你的物品上",
    "ONE random stat": "一个随机属性",
    "Paladin": "圣骑士",
    "Party Names": "队伍名称",
    "PARTY RESTORED 40% HP & MANA": "团队恢复40%的生命值和法力值",
    "Party restored 40% HP and Mana": "团队恢复40%的生命值和法力值！",
    "Pet Collection": "宠物收藏",
    "Room is clear": "房间已清理",
    "Rune Inventory": "符文库存",
    "Rune Trial": "符文试验",
    "RUNES": "符文",
    "Select an Item to Bless": "选择一个物品来祝福",
    "Select Dungeon": "选择地下城",
    "Select Your Dungeon": "选择你的地下城",
    "SELECT YOUR DUNGEON": "选择你的地下城",
    "Show Fountain of Youth Popup": "显示青春之泉弹窗",
    "Show Treasure Room Popup": "显示宝藏房间弹出",
    "Stoneforge": "石炉",
    "Stoneforge:": "石炉：",
    "Summary Duration": "汇总持续时间",
    "Support • Healer": "辅助·治疗",
    "Time Taken:": "花费时间：",
    "Total Damage Dealt:": "造成的总伤害：",
    "Total Gold:": "累计金币：",
    "Tracking Categories:": "跟踪类别:",
    "Umbral Depths": "阴暗的深处",
    "Umbral:": "阴暗：",
    "Unchecked rarities will auto-sell": "未勾选的稀有度将自动出售",
    "Uncommon": "罕见",
    "Vault": "金库",
    "VAULT": "金库",
    "Victory/Defeat screen duration": "胜利/失败屏幕持续时间",
    "Visit the Pet Collection tab to equip a pet": "进入宠物收集选项卡来装备宠物",
    "Your progress has been saved. Are you sure you want to leave?": "您的进度已被保存。你确定要离开吗？",
    "START ADVENTURE": "开始冒险",
    "Forest Wolf": "森林狼",
    "Got It! 🚀": "我知道了! 🚀",
    "Empty Slot": "空槽位",
    "Equip": "装备",
    "Equipped Pets": "已装备宠物",
    "OPEN": "打开",
    "SELL": "出售",
    "Unlock in Skill Tree": "在技能树解锁",
    "Victory": "胜利",
    "Auto-Equip Best": "自动装备最佳",
    "Autumn Wisp": "秋日小精灵",
    "Bandit Cutthroat": "强盗杀手",
    "Briar Spider": "荆棘蜘蛛",
    " None": "无",
    "Defeat enemies to collect pets": "击败敌人可以收集宠物",
    "Expand All": "全部展开",
    "Inventory is empty": "库存是空的",
    "Moss Boar": "苔藓野猪",
    "No keystones found": "没有找到钥匙石",
    "No loot available": "没有战利品可用",
    "No pets found yet": "暂未找到宠物",
    "No Runes found": "没有找到符文",
    "casts Divine Shield! All allies gain shields": "施放神圣之盾！所有盟友获得护盾",
    "grants 15% max HP shields to all allies": "给予所有盟友15%的最大生命值护盾",
    "Rotting Treant": "腐树怪",
    "Unlock Rune Slots in the Skill Tree": "解锁技能树中的符文槽",
    "⚜️ ELITE: Treasure Guardian": "⚜️ 精英：宝藏守护者",
    "🏆 TREASURE ROOM 🏆": "🏆 宝藏室 🏆",
    "💀 ELITE": "💀 精英",
    "Everfall - Floor 1 - Treasury": "永陨落 - 层 1 - 宝藏",
    "Treasure Guardians Protect This Room": "宝藏守护者守护着这个房间",
    "Colossus Of Iron": "钢铁巨像",
    "⚔️ VICTORY! ⚔️": "⚔️胜利!⚔️",
    "💀 DEFEAT 💀": "💀失败💀",
    "Anvil Guard": "铁砧守卫",
    "Boss defeated! Floor complete": "Boss被打败了！楼层完成",
    "Boss Loot Acquired": "获得Boss战利品",
    "Damage Dealt:": "造成的伤害：",
    "Ember Sprite": "灰烬精灵",
    "Forge Golem": "锻造魔像",
    "Molten Slime": "熔融史莱姆",
    "Oreback Beetle": "牛背甲虫",
    "Party defeated": "队伍失败",
    "Party respawns...": "团队重生...",
    "Quarry Brute": "采石场野兽",
    "Smelter Imp": "熔炼小恶魔",
    "Tunnel Rat": "隧道老鼠",
    "Red Stag": "红鹿",
    "items!": "物品!",
    ", forcing them to attack the Tank. Grants": "，强制他们攻击坦克。获得",
    "+10 flat defense + 2% of total defense": "+10 浮动防御 +2% 总防御",
    "1. Double Strike": "1. 双重打击",
    "1. Taunt": "1. 嘲讽",
    "defeats Gloomling": "击败暗影幼体",
    "defeats Night Stalker": "击败夜行者",
    "Dread Bat": "恐怖蝙蝠",
    "during taunt (scales": "嘲讽期间 (缩放",
    "Equip a Rogue Keystone from the Keystones tab to unlock a powerful second ability": "从“钥匙石”选项卡装备一个盗贼的钥匙石来解锁一个强大的第二技能",
    "Equip a Tank Keystone from the Keystones tab to unlock a powerful second ability": "从“钥匙石”选项中装备一个“坦克钥匙石”来解锁强大的第二个技能",
    "Gloomling": "暗影幼体",
    "Night Stalker": "夜行者",
    "Shade": "阴影",
    "Strikes twice, dealing": "连续攻击2次，造成",
    "taunts all enemies": "嘲讽所有敌人",
    "Taunts all enemies for": "嘲讽全体敌人持续",
    "total attack damage (scales": "总攻击伤害 (缩放",
    "Void Mite": "虚空螨",
    "• Frontline": "• 前线",
    "🔒 You need a Rune Trial Key to enter! Keys drop from floor 45+ (10% chance).": "🔒 你需要符文试炼钥匙才能进入！钥匙从45层掉落+（10%几率）。",
    "🔒 You need a Vault Key to enter! Keys drop from clearing floors (10% chance).": "🔒 你需要金库钥匙才能进入！通关楼层可以掉落钥匙（10%几率）",
    "(Dead)": "(死亡)",
    "Hollow Cultist": "空心教徒",
    "Abyssal Leech": "深渊吸血怪",
    "Hollow Cultist": "空心教徒",
    "Score": "分数",
    "Rank": "排名",
    "Player": "玩家",
    "Not Yet Ranked": "暂未上榜",
    "TOP 10 PLAYERS": "前 10 玩家",
    "Updates every 30 minutes": "每30分钟更新一次",
    "Your Stats": "你的统计",
    "Umbral Wisp": "暗影精灵",
    "Close": "关闭",
    "⚔️ TOP GEAR SCORES ⚔️": "⚔️ 最高 装备 评分 ⚔️",
    "GO": "出发",
    "Select a Vault Key to enter the Vault": "选择一个金库钥匙以进入金库",
    "CANCEL": "取消",
    "EQUIP": "装备",
    "GRITBUN": "砂砾兔",
    "Gritbun": "砂砾兔",
    "RELEASE": "释放",
    "Select a character:": "选择一个角色：",
    "UPGRADE": "升级",
    "UNEQUIP PET": "卸下宠物",
    "-DODGE": "-闪避",
    "Maw Of Deep": "深渊之肚",
    "common items will auto-sell": "自动出售 普通物品",
    "uncommon items will auto-sell": "自动出售 罕见物品",
    "rare items will auto-sell": "自动出售 稀有物品",
    "epic items will auto-sell": "自动出售 史诗物品",
    "ENTER": "进入",
    "ENTER VAULT?": "进入金库?",
    "This key will be consumed": "这把钥匙会被消耗掉",
    "Unequip": "卸下",
    "💚 Healing & Shielding": "💚 治疗 & 护盾",
    "No Rune Trial Keys! Keys drop from floor 45+ (10% chance).": "没有符文试炼钥匙！钥匙从45层掉落+（10%几率）。",
    "Elder Treant": "老树精",
    "Foundry Master": "铸造大师",
    "LOOFIN": "洛夫因",
    "Loofin": "洛夫因",
    "equipped Loofin": "已装备 洛夫因",
    "Night Herald": "暗夜使者",
    "Blessing Effects:": "祝福效果:",
    "• +50% to ONE random stat on this item": "• 该物品的一个随机属性+50%",
    "• Adds a purple blessing glow": "• 增加紫色祝福光芒",
    "• Permanent upgrade (cannot be removed)": "• 永久升级（不能移除）",
    "• Works on all rarities, including Mythic": "• 用于所有稀有，包括神话",
    "⚔️ Kills 10-20: VICTORY (Basic Rewards)": "⚔️ 击杀10-20：胜利（基础奖励）",
    "⚠️ Important:": "⚠️ 重要:",
    "⚡ Kills 21-39: Enhanced Rewards": "⚡ 击杀21-39：增强奖励",
    "✨ Divine Arena Drop Table ✨": "✨ 神圣竞技场掉落表✨",
    "✨ Kills 160-179: Godly Rewards": "✨ 击杀160-179：神圣的奖励",
    "❌ No item rewards (Victory threshold not reached)": "❌ 没有道具奖励（没有达到胜利门槛）",
    "⭐ Kills 80-99: Exceptional Rewards": "⭐ 击杀80-99：特殊奖励",
    "🌌 Kills 200+: TRANSCENDENT": "🌌 击杀200+：超越",
    "🌟 Kills 100-119: Masterwork Rewards": "🌟 击杀100-119：杰作奖励",
    "🎯 Item Level:": "🎯 物品等级：",
    "👑 Kills 180-199: Ultimate Rewards": "👑 击杀180-199：终极奖励",
    "💀 Kills 1-9: DEFEAT": "💀 击杀1-9：失败",
    "💎 Kills 120-139: Legendary Rewards": "💎 击杀120-139：传说奖励",
    "💎 Mythic:": "💎 神话:",
    "💎 Rarity:": "💎 稀有度：",
    "💡 Pro Tip:": "💡 专业提示：",
    "💫 Kills 60-79: Elite Rewards": "💫 击杀60-79：精英奖励",
    "📊 End of Run Rewards:": "📊 运行结束奖励：",
    "🔥 Kills 40-59: Superior Rewards": "🔥 击杀40-59：高级奖励",
    "🔮 Kills 140-159: Mythic Tier": "🔮 击杀140-159：神话层",
    "🔵 Rare:": "🔵 稀有：",
    "🟠 Legendary:": "🟠 传说：",
    "🟣 Epic:": "🟣 史诗:",
    "3 items awarded based on total kills": "根据总击杀奖励3件物品",
    "Determined by kill count brackets below": "由以下括号内的击杀数决定",
    "Item level scales with enemy level in Divine Arena. The deeper you push, the higher level items you'll receive! Mythic items also grant +5 item levels bonus.": "神圣竞技场的物品等级随敌人等级而变化。推进越深，获得的道具等级越高！神话物品也给予+5的物品等级加成。",
    "Need 10+ kills to earn any loot (Victory threshold)": "击杀10+才能获得战利品（胜利门槛）",
    "Please wait 3 seconds before changing dungeons.": "请等待3秒后再更换地下城。",
    "Scales with enemy level (increases as you progress)": "随着敌人等级的增加而增加（随着你的进步而增加）",
    "⚔️ Divine Arena! Survive endless waves": "⚔️ 神圣竞技场！在无尽的波次中生存下来",
    "⚔️ WARRIOR": "⚔️ 战士",
    "✨ Blessings Earned:": "✨ 获得的祝福：",
    "💀 Final Enemy Level:": "💀 最终敌人等级：",
    "💎 Blessing Rewards: 1/kill (1-19), 2/kill (20-29), 3/kill (30-39), 4/kill (40-49), 5/kill (50+)": "💎 祝福奖励：1/杀（1-19），2/杀（20-29），3/杀（30-39），4/杀（40-49），5/杀（50+）",
    "💰 Gold Earned:": "💰 获得金币：",
    "🔥 Damage Dealt:": "🔥 造成伤害：",
    "Blessings Earned:": "获得祝福：",
    "Character Performance": "角色表现",
    "DIVINE ARENA": "神圣竞技场",
    "Final Enemy Level:": "最终敌人等级：",
    "Frost Leviathan": "冰霜利维坦",
    "Infernal Behemoth": "地狱巨兽",
    "Reach 10 kills for arena rewards": "击杀数达到10可获得竞技场奖励",
    "Time Survived:": "生存时间：",
    "Titan Colossus": "泰坦巨像",
    "Total Kills:": "总击杀数：",
    "Waves Completed:": "完成波次：",
    "⏸️ Pause": "⏸️ 暂停",
    "▶️ Resume": "▶️ 继续",
    "RARE": "稀有",
    "Boots": "靴子",
    "Belt": "腰带",
    "🗡️ Rogue": "🗡️ 刺客",
    "EPIC": "史诗",
    "⚔️ DIVINE ARENA KILLS ⚔️": "⚔️ 神圣竞技场击杀 ⚔️",
    "✨ MOST MYTHICS FOUND ✨": "✨ 最多神话发现 ✨",
    "🏆 HIGHEST FLOORS 🏆": "🏆 最高层数 🏆",
    "🐾 MOST PETS FOUND 🐾": "🐾 最多宠物发现 🐾",
    "Keystone Warden": "钥匙石典狱长",
    "🔑 Keystone Reward 🔑": "🔑 钥匙石奖励 🔑",
    "🔒 VAULT BOSS KILLS 🔒": "🔒 金库Boss击杀 🔒",
    "🔮 RUNE TRIAL BOSS KILLS 🔮": "🔮 符文试炼Boss击杀 🔮",
    "2. Shadow Step": "2. 影步",
    "defeats Keystone Warden": "失败梯形监狱长",
    "defeats Warden Hound": "击败猎犬典狱长",
    "enters the shadows": "进入阴影",
    "Gold Earned": "获得的金币",
    "Keystone Warden appears": "钥匙石典狱长出现了",
    "Keystone Warden appears! HP: 5000": "钥匙石典狱长出现了！生命值：5000",
    "Keystone Warden summons a Warden Hound": "钥匙石典狱长召唤一只典狱长猎犬",
    "Next 3 attacks deal +120% damage and heal you for 50% of damage dealt": "接下来的3次攻击造成+120%的伤害，并治疗你50%伤害的生命值",
    "Shadow Step": "影步",
    "Shadow Step (30s CD |": "影步 (30秒 冷却 |",
    "Vault conquered": "金库被征服了",
    "VAULT CONQUERED": "金库被征服了",
    "Vault conquered! Select your next dungeon...": "金库被征服了！选择你的下一个地下城…",
    "XP Per Member": "经验值每位成员",
    "Free": "免费",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "belt": "腰带",
    "amulet": "护身符",
    "weapon": "武器",
    "ring1": "戒指1",
    "ring2": "戒指2",
    "gloves": "手套",
    "chest": "胸甲",
    "DPS:": "DPS:",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "⋮⋮": "⋮⋮",
    "▼": "▼",
    "✨": "✨",
    "🐾": "🐾",
    "🏆": "🏆",
    "💰": "💰",
    ").": ").",
    "?": "?",
    "--": "--",
    "•": "•",
    "⚔️": "⚔️",
    "💀": "💀",
    "🥇": "🥇",
    "🥈": "🥈",
    "🥉": "🥉",
    "✕": "✕",
    "🔑": "🔑",
    "×": "×",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "⚔️ DMG: ": "⚔️ 伤害: ",
    "SORT: ": "排序: ",
    "Dungeon Name - Floor ": "地下城名称 - 层数 ",
    "Pet Collection ": "宠物收藏 ",
    "NEW: ": "新: ",
    "DEF +": "防御 +",
    "Will equip to: ": "将装备到: ",
    "CURRENT: ": "当前：",
    "👑 BOSS: ": "👑 BOSS: ",
    "Paladin ": "圣骑士 ",
    "Mage ": "法师 ",
    "Archer ": "射手 ",
    "Tank ": "坦克 ",
    "Healer ": "治疗师 ",
    "Rogue ": "刺客 ",
    "Found pet: ": "发现宠物: ",
    "🐇 Gritbun (Lv.": "🐇 砂砾兔 (等级 ",
    "🎮 Version: ": "🎮 版本: ",
    "DODGE: +": "闪避: +",
    "Dodge: +": "闪避: +",
    "COMMON • Lv": "普通 • 等级",
    "Common • Level ": "普通 • 等级 ",
    "EQUIP ": "装备 ",
    "Auto-sold common item for ": "自动出售 普通物品 获得了 ",
    "Loot filter: ": "战利品过滤器: ",
    "Recommended: ": "推荐: ",
    "⭐ Bless Item ": "⭐ 祝福物品 ",
    "💚 HEAL+SHIELD: ": "💚 治疗+护盾: ",
    "🌊 Loofin (Lv.": "🌊 洛夫因 (等级",
    "Mana: +": "法力: +",
    "MANA: +": "法力: +",
    "Equipped on Archer • ": "射手 装备 • ",
    "Equipped on Healer • ": "治疗师 装备 • ",
    "Equipped on Rogue • ": "刺客 装备 • ",
    "Equipped on Tank • ": "坦克 装备 • ",
    "Equipped on Paladin • ": "坦克 圣骑士 • ",
    "Equipped on Mage • ": "法师 装备 • ",
    "Return to Dungeon Selector": "返回到地下城选择页面",
    "Return to Dungeon Selection": "返回到地下城选择页面",
    "Found a ✨ MYTHIC CHEST (Level ": "发现一个 ✨ 神话宝箱 (等级 ",
    "Vault Guardian drops Lvl ": "金库守护者 掉落 等级",
    "Umbral Wisp drops Lvl ": "暗影精灵 掉落 等级",
    "Hollow Stag drops Lvl ": "空心雄鹿 掉落 等级",
    "Found 🛡️ Tank keystone: ": "发现 🛡️ 坦克 钥匙石: ",
    "Found 🏹 Archer keystone: ": "发现 🏹 射手 钥匙石: ",
    "Found 💊 Healer keystone: ": "发现 💊 治疗师 钥匙石: ",
    "Found 🗡️ Rogue keystone: ": "发现 🗡️ 刺客 钥匙石: ",
    "💎 BOSS: ": "💎 BOSS: ",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    '!': '!',
    " sent to inventory (not an upgrade)": " 发送到库存（不是升级）",
    " Common Shadow Dancer": " 普通影舞者",
    " Common Dagger": " 普通匕首",
    " Common Greatsword": " 普通巨剑",
    " Common Ring": " 普通戒指",
    " Common Amulet": " 普通护身符",
    " Common Gloves": " 普通手套",
    " Common Belt": " 普通腰带",
    " Common Boots": " 普通靴子",
    " Common Staff": " 普通法杖",
    " Common Wand": " 普通权杖",
    " Common Helmet": " 普通头盔",
    " Common Bow": " 普通弓",
    " Common Warhammer": " 普通战锤",
    " Common Chestplate": " 普通板甲",
    " Legendary Dagger": " 传说匕首",
    " Legendary Greatsword": " 传说巨剑",
    " Legendary Ring": " 传说戒指",
    " Legendary Amulet": " 传说护身符",
    " Legendary Gloves": " 传说手套",
    " Legendary Belt": " 传说腰带",
    " Legendary Boots": " 传说靴子",
    " Legendary Staff": " 传说法杖",
    " Legendary Wand": " 传说权杖",
    " Legendary Helmet": " 传说头盔",
    " Legendary Bow": " 传说弓",
    " Legendary Warhammer": " 传说战锤",
    " Legendary Chestplate": " 传说板甲",
    " Rare Dagger": " 稀有匕首",
    " Rare Greatsword": " 稀有巨剑",
    " Rare Ring": " 稀有戒指",
    " Rare Amulet": " 稀有护身符",
    " Rare Gloves": " 稀有手套",
    " Rare Belt": " 稀有腰带",
    " Rare Boots": " 稀有靴子",
    " Rare Staff": " 稀有法杖",
    " Rare Wand": " 稀有权杖",
    " Rare Helmet": " 稀有头盔",
    " Rare Bow": " 稀有弓",
    " Rare Warhammer": " 稀有战锤",
    " Rare Chestplate": " 稀有板甲",
    " Epic Dagger": " 史诗匕首",
    " Epic Greatsword": " 史诗巨剑",
    " Epic Ring": " 史诗戒指",
    " Epic Amulet": " 史诗护身符",
    " Epic Gloves": " 史诗手套",
    " Epic Belt": " 史诗腰带",
    " Epic Boots": " 史诗靴子",
    " Epic Staff": " 史诗法杖",
    " Epic Wand": " 史诗权杖",
    " Epic Helmet": " 史诗头盔",
    " Epic Bow": " 史诗弓",
    " Epic Warhammer": " 史诗战锤",
    " Epic Chestplate": " 史诗板甲",
    " Uncommon Dagger": " 罕见匕首",
    " Uncommon Greatsword": " 罕见巨剑",
    " Uncommon Ring": " 罕见戒指",
    " Uncommon Amulet": " 罕见护身符",
    " Uncommon Gloves": " 罕见手套",
    " Uncommon Belt": " 罕见腰带",
    " Uncommon Boots": " 罕见靴子",
    " Uncommon Staff": " 罕见法杖",
    " Uncommon Wand": " 罕见权杖",
    " Uncommon Helmet": " 罕见头盔",
    " Uncommon Bow": " 罕见弓",
    " Uncommon Warhammer": " 罕见战锤",
    " Uncommon Chestplate": " 罕见板甲",
    "defeats Night Stalker": " 击败了 夜行者",
    "defeats Shade": " 击败了 阴影",
    "defeats Gloomling": " 击败了 暗影幼体",
    "defeats Dread Bat": " 击败了 恐惧蝙蝠",
    "defeats Foundry Master": " 击败了 铸造大师",
    "defeats Tunnel Rat": " 击败了 隧道老鼠",
    "defeats Smelter Imp": " 击败了 熔炼小恶魔",
    "defeats Quarry Brute": " 击败了 采石场野兽",
    "defeats Oreback Beetle": " 击败了 牛背甲虫",
    "defeats Molten Slime": " 击败了 熔融史莱姆",
    "defeats Forge Golem": " 击败了 锻造魔像",
    "defeats Treasure Guardian": " 击败了 宝藏守护者",
    "defeats Ember Sprite": " 击败了 灰烬精灵",
    "defeats Anvil Guard": " 击败了 铁砧守卫",
    "defeats Fallen Scout": " 击败了 陨落的侦察兵",
    "defeats Forest Wolf": " 击败了 森林狼",
    "defeats Elder Treant": " 击败了 老树精",
    "defeats Night Herald": " 击败了 暗夜使者",
    "defeats Red Stag": " 击败了 红鹿",
    "defeats Autumn Wisp": " 击败了 秋日小精灵",
    "defeats Abyssal Leech": "击败深渊吸血怪",
    "defeats Hollow Cultist": "击败空心教徒",
    "defeats Void Mite": "击败虚空螨",
    "defeats Bandit Cutthroat": " 击败了 盗匪杀手",
    "defeats Umbral Wisp": " 击败了 暗影精灵",
    "defeats Briar Spider": " 击败了 荆棘蜘蛛",
    "defeats Colossus Of Iron": " 击败了 钢铁巨像",
    "defeats Moss Boar": " 击败了 苔藓野猪",
    "defeats Rotting Treant": " 击败了 腐树怪",
    "defeats Maw Of Deep": " 击败了深渊之肚",
    "defeats Hollow Stag": " 击败了空心雄鹿",
    " (Dead)": " (死亡)",
    " appears with minions": " 带着小怪出现了",
    " - Fountain of Youth": " - 青春之泉",
    " - Entrance": " - 入口",
    " - Treasury": " - 宝藏",
    " - Chamber": " - 密室",
    " - Boss Lair": " - Boss巢穴",
    " (rarity filtered)": " (按稀有度过滤)",
    "! Access Vault in Cache tab.": "! 在物资选项卡中访问金库。",
    "Mana Cost:": "法力成本:",
    " (level filtered)": " (等级过滤)",
    " Martyr's Blessing": " 殉道者的祝福",
    " Serpent's Venom": " 普通蛇毒",
    " Earthshaker\'s Resolve": " 震地者的决心",
    " Assassin\'s Mark": " 震刺客印记",
    " Hunter\'s Focus": " 猎人的焦点",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\% \|$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.,]+) \(([\d\.]+)\%\)$/,
    /^([\d\.]+) \(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+) ✨$/,
    /^x([\d\.,]+)$/,
    /^\#([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^⭐ ([\d\.,]+)$/,
    /^⚔️ ([\d\.,]+)$/,
    /^🛡️ ([\d\.,]+)$/,
    /^💥 ([\d\.,]+)$/,
    /^💚 ([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Using Level (.+) Vault Key! Entering boss fight...$/, '使用 $1 级金库钥匙！进入boss战...'],
    [/^Loot odds: (.+) Legendary, (.+) Epic, (.+) Rare$/, '战利品几率：$1 传说，$2 史诗，$3 稀有'],
    [/^Found a Level (.+) Chest from Umbral Depths! \(Open: (.+)g, Sell: (.+)g\). See Chests tab.$/, '从 阴暗的深处 找到一个 $1 级宝箱！（开启：$2金币，出售：$3金币）。参见宝箱选项卡。'],
    [/^Found a Level (.+) Chest from Everfall! \(Open: (.+)g, Sell: (.+)g\). See Chests tab.$/, '从 永恒陨落 找到一个 $1 级宝箱！（开启：$2金币，出售：$3金币）。参见宝箱选项卡。'],
    [/^Each guardian drops (.+) gold$/, '每个守护者掉落 $1 金币'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^SELECT (.+) MORE HEROES$/, '请选择 $1 个英雄'],
    [/^SELECT (.+) MORE HEROE$/, '请选择 $1 个英雄'],
    [/^taunts all enemies! \(\+(.+) DEF \[\+(.+) \+ (.+)\%\] for (.+)s\)$/, '嘲讽所有敌人！（+$1 防御 [+$2 + $3%] 持续 $4 秒）'],
    [/^Auto-sold level (.+) item for (.+)g$/, '自动出售 等级 $1 的物品 获得了 $2 金币'],
    [/^Auto-sold uncommon item for (.+)g$/, '自动出售 罕见物品 获得了 $1 金币'],
    [/^Auto-sold common item for (.+)g$/, '自动出售 普通物品 获得了 $1 金币'],
    [/^Auto-sold rare item for (.+)g$/, '自动出售 稀有物品 获得了 $1 金币'],
    [/^Auto-sold epic item for (.+)g$/, '自动出售 史诗物品 获得了 $1 金币'],
    [/^Auto-sold legendary item for (.+)g$/, '自动出售 传说物品 获得了 $1 金币'],
    [/^Auto-sold mythic item for (.+)g$/, '自动出售 神话物品 获得了 $1 金币'],
    [/^Sold Lvl (.+) Common Gloves for (.+)g$/, '出售 等级 $1 普通手套 获得了 $2 金币'],
    [/^Sold Lvl (.+) Common Helmet for (.+)g$/, '出售 等级 $1 普通头盔 获得了 $2 金币'],
    [/^Sold Lvl (.+) Common Chestplate for (.+)g$/, '出售 等级 $1 普通板甲 获得了 $2 金币'],
    [/^Sold Lvl (.+) Common Boots for (.+)g$/, '出售 等级 $1 普通靴子 获得了 $2 金币'],
    [/^Sold Lvl (.+) Common Bow for (.+)g$/, '出售 等级 $1 普通弓 获得了 $2 金币'],
    [/^Sold Lvl (.+) Common Greatsword for (.+)g$/, '出售 等级 $1 普通巨剑 获得了 $2 金币'],
    [/^Sold Lvl (.+) Common Staff for (.+)g$/, '出售 等级 $1 普通法杖 获得了 $2 金币'],
    [/^Sold Lvl (.+) Common Ring for (.+)g$/, '出售 等级 $1 普通戒指 获得了 $2 金币'],
    [/^Sold Lvl (.+) Common Dagger for (.+)g$/, '出售 等级 $1 普通匕首 获得了 $2 金币'],
    [/^Sold Lvl (.+) Common Amulet for (.+)g$/, '出售 等级 $1 普通护身符 获得了 $2 金币'],
    [/^Sold Lvl (.+) Uncommon Gloves for (.+)g$/, '出售 等级 $1 罕见手套 获得了 $2 金币'],
    [/^Sold Lvl (.+) Uncommon Helmet for (.+)g$/, '出售 等级 $1 罕见头盔 获得了 $2 金币'],
    [/^Sold Lvl (.+) Uncommon Chestplate for (.+)g$/, '出售 等级 $1 罕见板甲 获得了 $2 金币'],
    [/^Sold Lvl (.+) Uncommon Boots for (.+)g$/, '出售 等级 $1 罕见靴子 获得了 $2 金币'],
    [/^Sold Lvl (.+) Uncommon Bow for (.+)g$/, '出售 等级 $1 罕见弓 获得了 $2 金币'],
    [/^Sold Lvl (.+) Uncommon Greatsword for (.+)g$/, '出售 等级 $1 罕见巨剑 获得了 $2 金币'],
    [/^Sold Lvl (.+) Uncommon Staff for (.+)g$/, '出售 等级 $1 罕见法杖 获得了 $2 金币'],
    [/^Sold Lvl (.+) Uncommon Ring for (.+)g$/, '出售 等级 $1 罕见戒指 获得了 $2 金币'],
    [/^Sold Lvl (.+) Uncommon Dagger for (.+)g$/, '出售 等级 $1 罕见匕首 获得了 $2 金币'],
    [/^Sold Lvl (.+) Uncommon Amulet for (.+)g$/, '出售 等级 $1 罕见护身符 获得了 $2 金币'],
    [/^Sold Lvl (.+) Rare Gloves for (.+)g$/, '出售 等级 $1 稀有手套 获得了 $2 金币'],
    [/^Sold Lvl (.+) Rare Helmet for (.+)g$/, '出售 等级 $1 稀有头盔 获得了 $2 金币'],
    [/^Sold Lvl (.+) Rare Chestplate for (.+)g$/, '出售 等级 $1 稀有板甲 获得了 $2 金币'],
    [/^Sold Lvl (.+) Rare Boots for (.+)g$/, '出售 等级 $1 稀有靴子 获得了 $2 金币'],
    [/^Sold Lvl (.+) Rare Bow for (.+)g$/, '出售 等级 $1 稀有弓 获得了 $2 金币'],
    [/^Sold Lvl (.+) Rare Greatsword for (.+)g$/, '出售 等级 $1 稀有巨剑 获得了 $2 金币'],
    [/^Sold Lvl (.+) Rare Staff for (.+)g$/, '出售 等级 $1 稀有法杖 获得了 $2 金币'],
    [/^Sold Lvl (.+) Rare Ring for (.+)g$/, '出售 等级 $1 稀有戒指 获得了 $2 金币'],
    [/^Sold Lvl (.+) Rare Dagger for (.+)g$/, '出售 等级 $1 稀有匕首 获得了 $2 金币'],
    [/^Sold Lvl (.+) Rare Amulet for (.+)g$/, '出售 等级 $1 稀有护身符 获得了 $2 金币'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Attack Speed: ([\d\.]+)\/s$/, '攻击速度: $1/秒'],
    [/^Loot Drop: ([\d\.]+)\%$/, '战利品掉率: $1%'],
    [/^E ([\d\.]+)\%$/, '史诗 $1%'],
    [/^L ([\d\.]+)\%$/, '传说 $1%'],
    [/^R ([\d\.]+)\%$/, '稀有 $1%'],
    [/^M ([\d\.]+)\%$/, '神话 $1%'],
    [/^([\d\.]+)\/s$/, '$1/秒'],
    [/^\-([\d\.]+) CRIT$/, '-$1 暴击'],
    [/^⚔️ \+([\d\.]+) Attack$/, '⚔️ +$1 攻击'],
    [/^⚡ \+([\d\.]+) Attack Speed$/, '⚡ +$1 攻击速度'],
    [/^🛡️ \+([\d\.]+) Defense$/, '🛡️ +$1 防御'],
    [/^❤️ \+([\d\.]+) HP$/, '❤️ +$1 生命值'],
    [/^💙 \+([\d\.]+) Mana$/, '💙 +$1 法力值'],
    [/^💜 \+([\d\.]+) Mana Regen$/, '💜 +$1 法力回复'],
    [/^⏱️ \+([\d\.]+)\% CDR$/, '⏱️ +$1% CDR'],
    [/^🌀 \+([\d\.]+)\% Dodge$/, '🌀 +$1% 闪避'],
    [/^💢 \+([\d\.]+)\% Crit Damage$/, '💢 +$1% 暴击伤害'],
    [/^💥 \+([\d\.]+)\% Crit Chance$/, '💥 +$1% 暴击几率'],
    [/^🩸 \+([\d\.]+)\% Lifesteal$/, '🩸 +$1% 吸血'],
    [/^✨ Bless \(([\d\.]+) 💎\)$/, '✨ 祝福 ($1 💎)'],
    [/^\+([\d\.]+) Attack Speed$/, '+$1 攻击速度'],
    [/^\+([\d\.]+) Mana$/, '+$1 法力值'],
    [/^\+([\d\.]+) Attack$/, '+$1 攻击'],
    [/^\+([\d\.]+) HP$/, '+$1 生命值'],
    [/^\+([\d\.]+) HP Regen$/, '+$1 生命值回复'],
    [/^HP \+([\d\.]+)$/, '生命值 +$1'],
    [/^ATK \+([\d\.]+)$/, '攻击 +$1'],
    [/^ATK \+([\d\.]+), HP \+([\d\.]+)$/, '攻击 +$1, 生命值 +$2'],
    [/^ATK \+([\d\.]+), MANA \+([\d\.]+)$/, '攻击 +$1, 法力 +$2'],
    [/^ATK \+([\d\.]+), CDR \+([\d\.]+)\%$/, '攻击 +$1, CDR +$2%'],
    [/^CRIT \+([\d\.]+)\%, CRIT DMG \+([\d\.]+)\%$/, '暴击 +$1%, 暴击伤害 +$2%'],
    [/^ATK \+([\d\.]+), CRIT DMG \+([\d\.]+)\%$/, '攻击 +$1, 暴击伤害 +$2%'],
    [/^ATK SPD \+([\d\.]+), CRIT \+([\d\.]+)\%$/, '攻击速度 +$1, 暴击 +$2%'],
    [/^HP \+([\d\.]+), CRIT DMG \+([\d\.]+)\%$/, '生命值 +$1, 暴击伤害 +$2%'],
    [/^HP \+([\d\.]+), DEF \+([\d\.]+), LIFESTEAL \+([\d\.]+)\%$/, '生命值 +$1, 防御 +$2, 吸血 +$3%'],
    [/^HP \+([\d\.]+), MANA \+([\d\.]+), CDR \+([\d\.]+)\%$/, '生命值 +$1, 法力 +$2, CDR +$3%'],
    [/^HP \+([\d\.]+), LIFESTEAL \+([\d\.]+)\%, HP REGEN \+([\d\.]+)\%$/, '生命值 +$1, 吸血 +$2%, 生命值回复 +$3%'],
    [/^HP \+([\d\.]+), MANA \+([\d\.]+), DODGE \+([\d\.]+)\%$/, '生命值 +$1, 法力 +$2, 闪避 +$3%'],
    [/^HP \+([\d\.]+), MANA \+([\d\.]+), DEF \+([\d\.]+)$/, '生命值 +$1, 法力 +$2, 防御 +$3'],
    [/^HP \+([\d\.]+), MANA \+([\d\.]+), DEF \+([\d\.]+), CDR \+([\d\.]+)\%$/, '生命值 +$1, 法力 +$2, 防御 +$3, CDR +$4%'],
    [/^HP \+([\d\.]+), DEF \+([\d\.]+), LIFESTEAL \+([\d\.]+)\%, HP REGEN \+([\d\.]+)$/, '生命值 +$1, 防御 +$2, 吸血 +$3%, 生命值回复 +$4'],
    [/^HP \+([\d\.]+), DEF \+([\d\.]+), DODGE \+([\d\.]+)\%$/, '生命值 +$1, 防御 +$2, 闪避 +$3%'],
    [/^HP \+([\d\.]+), DEF \+([\d\.]+), CDR \+([\d\.]+)\%$/, '生命值 +$1, 防御 +$2, CDR +$3%'],
    [/^MANA \+([\d\.]+), DEF \+([\d\.]+), CDR \+([\d\.]+)\%$/, '法力 +$1, 防御 +$2, CDR +$3%'],
    [/^MANA REGEN \+([\d\.]+), CDR \+([\d\.]+)\%$/, '法力回复 +$1, CDR +$2%'],
    [/^ATK \+([\d\.]+), CRIT \+([\d\.]+)\%, CDR \+([\d\.]+)\%$/, '攻击 +$1, 暴击 +$2%, CDR +$3%'],
    [/^ATK \+([\d\.]+), CRIT DMG\+([\d\.]+)\%, MANA REGEN \+([\d\.]+)$/, '攻击 +$1, 暴击伤害 +$2%, 法力回复 +$3'],
    [/^ATK \+([\d\.]+), CRIT \+([\d\.]+)\%, LIFESTEAL \+([\d\.]+)\%$/, '攻击 +$1, 暴击 +$2%, 吸血 +$3%'],
    [/^ATK \+([\d\.]+), CRIT \+([\d\.]+)\%, CRIT DMG \+([\d\.]+)\%$/, '攻击 +$1, 暴击 +$2%, 暴击伤害 +$3%'],
    [/^ATK SPD \+([\d\.]+), CRIT \+([\d\.]+)\%, CRIT DMG \+([\d\.]+)\%$/, '攻击速度 +$1, 暴击 +$2%, 暴击伤害 +$3%'],
    [/^ATK \+([\d\.]+), MANA REGEN \+([\d\.]+), CDR \+([\d\.]+)\%$/, '攻击 +$1, 法力回复 +$2, CDR +$3%'],
    [/^ATK SPD \+([\d\.]+), HP \+([\d\.]+), DEF \+([\d\.]+)$/, '攻击速度 +$1, 生命值 +$2, 防御 +$3'],
    [/^ATK SPD \+([\d\.]+), HP \+([\d\.]+), DODGE \+([\d\.]+)\%$/, '攻击速度 +$1, 生命值 +$2, 闪避 +$3%'],
    [/^ATK SPD \+([\d\.]+), DEF \+([\d\.]+), DODGE \+([\d\.]+)\%$/, '攻击速度 +$1, 防御 +$2, 闪避 +$3%'],
    [/^ATK SPD \+([\d\.]+), CRIT \+([\d\.]+)\%, LIFESTEAL \+([\d\.]+)\%$/, '攻击速度 +$1, 暴击 +$2%, 吸血 +$3%'],
    [/^ATK \+([\d\.]+), ATK SPD \+([\d\.]+), DEF \+([\d\.]+)$/, '攻击 +$1, 攻击速度 +$2, 防御 +$3'],
    [/^ATK \+([\d\.]+), ATK SPD \+([\d\.]+), LIFESTEAL \+([\d\.]+)\%$/, '攻击 +$1, 攻击速度 +$2, 吸血 +$3%'],
    [/^ATK \+([\d\.]+), ATK SPD \+([\d\.]+), CRIT \+([\d\.]+)\%$/, '攻击 +$1, 攻击速度 +$2, 暴击 +$3%'],
    [/^ATK \+([\d\.]+), ATK SPD \+([\d\.]+), CRIT DMG \+([\d\.]+)\%$/, '攻击 +$1, 攻击速度 +$2, 暴击伤害 +$3%'],
    [/^ATK \+([\d\.]+), HP \+([\d\.]+), CRIT DMG \+([\d\.]+)\%$/, '攻击 +$1, 生命值 +$2, 暴击伤害 +$3%'],
    [/^ATK \+([\d\.]+), HP \+([\d\.]+), MANA REGEN \+([\d\.]+)$/, '攻击 +$1, 生命值 +$2, 法力回复 +$3'],
    [/^ATK \+([\d\.]+), HP \+([\d\.]+), DEF \+([\d\.]+)$/, '攻击 +$1, 生命值 +$2, 防御 +$3'],
    [/^ATK \+([\d\.]+), ATK SPD \+([\d\.]+), HP \+([\d\.]+)$/, '攻击 +$1, 攻击速度 +$2, 生命值 +$3'],
    [/^ATK \+([\d\.]+), ATK SPD \+([\d\.]+), HP \+([\d\.]+), DEF \+([\d\.]+)$/, '攻击 +$1, 攻击速度 +$2, 生命值 +$3, 防御 +$4'],
    [/^ATK \+([\d\.]+), ATK SPD \+([\d\.]+), CRIT \+([\d\.]+)\%, CRIT DMG \+([\d\.]+)\%$/, '攻击 +$1, 攻击速度 +$2, 暴击 +$3%, 暴击伤害 +$4%'],
    [/^ATK SPD \+([\d\.]+), HP \+([\d\.]+), DEF \+([\d\.]+), DODGE \+([\d\.]+)\%$/, '攻击速度 +$1, 生命值 +$2, 防御 +$3, 闪避 +$4%'],
    [/^HP \+([\d\.]+), MANA \+([\d\.]+), DEF \+([\d\.]+), DODGE \+([\d\.]+)\%$/, '生命值 +$1, 法力 +$2, 防御 +$3, 闪避 +$4%'],
    [/^ATK \+([\d\.]+), MANA \+([\d\.]+), MANA REGEN \+([\d\.]+)$/, '攻击 +$1, 法力 +$2, 法力回复 +$3'],
    [/^ATK \+([\d\.]+), MANA \+([\d\.]+), MANA REGEN \+([\d\.]+), CDR \+([\d\.]+)\%$/, '攻击 +$1, 法力 +$2, 法力回复 +$3, CDR +$4%'],
    [/^ATK \+([\d\.]+), HP \+([\d\.]+), DEF \+([\d\.]+), LIFESTEAL \+([\d\.]+)\%$/, '攻击 +$1, 生命值 +$2, 防御 +$3, 吸血 +$4%'],
    [/^CRIT \+([\d\.]+)\%$/, '暴击 +$1%'],
    [/^CRIT DMG \+([\d\.]+)\%$/, '暴击伤害 +$1%'],
    [/^\+([\d\.]+)\% HP Regen$/, '+$1% 生命值回复'],
    [/^\+([\d\.]+)\% Mana Regen$/, '+$1% 法力回复'],
    [/^\+([\d\.]+)\% CDR$/, '+$1% CDR'],
    [/^\+([\d\.]+)\% Dodge$/, '+$1% 闪避'],
    [/^\+([\d\.]+)\% Crit Chance$/, '+$1% 暴击率'],
    [/^\+([\d\.]+)\% Crit Damage$/, '+$1% 暴击伤害'],
    [/^\+([\d\.]+)\% Dodge Chance$/, '+$1% 闪避几率'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% Lifesteal$/, '+$1% 吸血'],
    [/^\+([\d\.]+)\% Lifesteal, \+([\d\.]+) HP Regen$/, '+$1% 吸血, +$2 生命值回复'],
    [/^\+([\d\.]+)\% Crit Chance, \+([\d\.]+)\% Crit Damage$/, '+$1% 暴击率, +$2% 暴击伤害'],
    [/^\+([\d\.]+) Mana Regen$/, '+$1% 法力回复'],
    [/^\+([\d\.]+) Mana, \+([\d\.]+) Defense$/, '+$1% 法力值, +$2 防御'],
    [/^\+([\d\.]+) Mana, \+([\d\.]+) Defense, \+([\d\.]+)% CDR$/, '+$1% 法力, +$2 防御, \+$3% CDR'],
    [/^\+([\d\.]+) HP, \+([\d\.]+) Mana Regen$/, '+$1% 生命值, +$2 法力回复'],
    [/^\+([\d\.]+) HP, \+([\d\.]+) Mana$/, '+$1% 生命值, +$2 法力值'],
    [/^\+([\d\.]+) HP, \+([\d\.]+) Defense, \+([\d\.]+) HP Regen$/, '+$1% 生命值, +$2 防御, \+$3 生命值回复'],
    [/^\+([\d\.]+) HP, \+([\d\.]+)\% Crit Damage$/, '+$1% 生命值, +$2% 暴击伤害'],
    [/^\+([\d\.]+) HP, \+([\d\.]+)\% Crit Damage, \+([\d\.]+) Mana Regen$/, '+$1% 生命值, +$2% 暴击伤害, \+$3 法力回复'],
    [/^\+([\d\.]+) HP, \+([\d\.]+) Mana, \+([\d\.]+) Defense$/, '+$1% 生命值, +$2 法力, \+$3 防御'],
    [/^\+([\d\.]+) HP, \+([\d\.]+) Mana, \+([\d\.]+)% CDR$/, '+$1% 生命值, +$2 法力, \+$3% CDR'],
    [/^\+([\d\.]+) HP, \+([\d\.]+) Defense, \+([\d\.]+)% CDR$/, '+$1% 生命值, +$2 防御, \+$3% CDR'],
    [/^\+([\d\.]+) HP, \+([\d\.]+) Defense, \+([\d\.]+)\% Lifesteal$/, '+$1% 生命值, +$2 防御, \+$3% 吸血'],
    [/^\+([\d\.]+) HP, \+([\d\.]+)\% CDR$/, '+$1% 生命值, +$2% CDR'],
    [/^\+([\d\.]+) HP, \+([\d\.]+) Defense, \+([\d\.]+)% Dodge$/, '+$1% 生命值, +$2 防御, \+$3% 闪避'],
    [/^\+([\d\.]+) HP, \+([\d\.]+) Mana, \+([\d\.]+)% Dodge$/, '+$1% 生命值, +$2 法力, \+$3% 闪避'],
    [/^\+([\d\.]+) HP, \+([\d\.]+) Mana, \+([\d\.]+) Defense, \+([\d\.]+)% Dodge$/, '+$1% 生命值, +$2 法力, +$3 防御, \+$4% 闪避'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Mana$/, '+$1% 攻击, +$2 法力值'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Mana Regen$/, '+$1% 攻击, +$2 法力回复'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Attack Speed$/, '+$1% 攻击, +$2 攻击速度'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) HP$/, '+$1% 攻击, +$2 生命值'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Defense$/, '+$1% 攻击, +$2 防御'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+)\% Crit Chance$/, '+$1% 攻击, +$2% 暴击率'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+)\% Crit Damage$/, '+$1% 攻击, +$2% 暴击伤害'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+)\% CDR$/, '+$1% 攻击, +$2% CDR'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) HP, \+([\d\.]+) Mana$/, '+$1% 攻击, +$2 生命值, \+$3 法力值'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Attack Speed, \+([\d\.]+) Defense$/, '+$1% 攻击, +$2 攻击速度, \+$3 防御'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) HP, \+([\d\.]+) Mana Regen$/, '+$1% 攻击, +$2 生命值, \+$3 法力值回复'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) HP, \+([\d\.]+) Defense$/, '+$1% 攻击, +$2 生命值, \+$3 防御'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) HP, \+([\d\.]+)\% Lifesteal$/, '+$1% 攻击, +$2 生命值, \+$3% 吸血'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Mana Regen, \+([\d\.]+)\% CDR$/, '+$1% 攻击, +$2 法力回复, \+$3% CDR'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Attack Speed, \+([\d\.]+)\% Crit Chance, \+([\d\.]+)\% Crit Damage$/, '+$1 攻击, +$2 攻击速度, \+$3% 暴击率, \+$4% 暴击伤害'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Attack Speed, \+([\d\.]+) HP, \+([\d\.]+) Defense$/, '+$1 攻击, +$2 攻击速度, \+$3 生命值, \+$4 防御'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) HP, \+([\d\.]+) Defense, \+([\d\.]+)\% Lifesteal$/, '+$1 攻击, +$2 生命值, \+$3 防御, \+$4% 吸血'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Mana, \+([\d\.]+) Mana Regen$/, '+$1 攻击, +$2 法力, \+$3 法力回复'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Mana, \+([\d\.]+)\% CDR$/, '+$1 攻击, +$2 法力, \+$3% CDR'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Mana, \+([\d\.]+) Mana Regen, \+([\d\.]+)\% CDR$/, '+$1 攻击, +$2 法力, \+$3 法力回复, \+$4% CDR'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+)\% Crit Damage, \+([\d\.]+) Mana Regen$/, '+$1% 攻击, +$2% 暴击伤害, \+$3 法力回复'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+)\% Crit Chance, \+([\d\.]+)\% CDR$/, '+$1% 攻击, +$2% 暴击率, \+$3% CDR'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+)\% Crit Chance, \+([\d\.]+)\% Lifesteal$/, '+$1% 攻击, +$2% 暴击率, \+$3% 吸血'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+)\% Crit Chance, \+([\d\.]+)\% Crit Damage$/, '+$1% 攻击, +$2% 暴击率, \+$3% 暴击伤害'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) HP, \+([\d\.]+)\% Crit Damage$/, '+$1% 攻击, +$2 生命值, \+$3% 暴击伤害'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Attack Speed, \+([\d\.]+)\% Lifesteal$/, '+$1% 攻击, +$2 攻击速度, \+$3% 吸血'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Attack Speed, \+([\d\.]+)\% CRIT, \+([\d\.]+)\% Lifesteal$/, '+$1% 攻击, +$2 攻击速度, \+$3% 暴击, \+$4% 吸血'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Attack Speed, \+([\d\.]+)\% Crit Chance$/, '+$1% 攻击, +$2 攻击速度, \+$3% 暴击率'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Attack Speed, \+([\d\.]+)\% Crit Chance, \+([\d\.]+)% Lifesteal$/, '+$1% 攻击, +$2 攻击速度, \+$3% 暴击率, \+$4% 吸血'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Attack Speed, \+([\d\.]+)\% Crit Damage$/, '+$1% 攻击, +$2 攻击速度, \+$3% 暴击伤害'],
    [/^\+([\d\.]+) Attack, \+([\d\.]+) Attack Speed, \+([\d\.]+) HP$/, '+$1% 攻击, +$2 攻击速度, \+$3 生命值'],
    [/^\+([\d\.]+) Attack Speed, \+([\d\.]+)\% Crit Chance, \+([\d\.]+)% Lifesteal$/, '+$1% 攻击速度, +$2% 暴击率, \+$3% 吸血'],
    [/^\+([\d\.]+) Attack Speed, \+([\d\.]+) HP$/, '+$1% 攻击速度, +$2 生命值'],
    [/^\+([\d\.]+) Attack Speed, \+([\d\.]+)\% Crit Damage$/, '+$1% 攻击速度, +$2% 暴击伤害'],
    [/^\+([\d\.]+) Attack Speed, \+([\d\.]+)\% Crit Chance$/, '+$1% 攻击速度, +$2% 暴击率'],
    [/^\+([\d\.]+) Attack Speed, \+([\d\.]+) HP, \+([\d\.]+) Defense$/, '+$1% 攻击速度, +$2 生命值, \+$3 防御'],
    [/^\+([\d\.]+) Attack Speed, \+([\d\.]+)\% Crit Chance, \+([\d\.]+)\% Crit Damage$/, '+$1% 攻击速度, +$2% 暴击率, \+$3% 暴击伤害'],
    [/^\+([\d\.]+) Defense, \+([\d\.]+)\% Lifesteal$/, '+$1% 防御, +$2% 吸血'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) items$/, '$1 物品'],
    [/^([\d\.,]+) Kills$/, '$1 击杀'],
    [/^([\d\.,]+) KILLS$/, '$1 击杀'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^([\d\.,]+) arrows$/, '$1 箭'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Treasure Guardians appear$/, '$1 宝藏守护者出现了'],
    [/^([\d\.,]+) enemies appear$/, '$1 敌人出现了'],
    [/^([\d\.,]+)g$/, '$1 金币'],
    [/^Sell ([\d\.,]+)g$/, '出售 $1 金币'],
    [/^\+([\d\.,]+)\% per rune tier$/, '每符文层级 +$1%'],
    [/^\+([\d\.,]+)\% max HP per rune tier$/, '每符文层级 +$1% 生命值上限'],
    [/^\+([\d\.,]+) Defense$/, '+$1 防御'],
    [/^\+([\d\.,]+)g$/, '+$1 金币'],
    [/^MANA REGEN \+([\d\.,]+)$/, '法力回复 +$1'],
    [/^([\d\.,]+)\/([\d\.,]+) HP$/, '$1/$2 生命值'],
    [/^([\d\.,]+)\/([\d\.,]+) HP \(🛡️([\d\.,]+)\)$/, '$1/$2 生命值 (🛡️$3)'],
    [/^([\d\.,]+)\/([\d\.,]+) XP$/, '$1/$2 经验值'],
    [/^([\d\.,]+)\/([\d\.,]+) MANA$/, '$1/$2 法力'],
    [/^SELECT ([\d\.,]+) HEROES$/, '选择 $1 英雄'],
    [/^SELECT ([\d\.,]+) HEROE$/, '选择 $1 英雄'],
    [/^HP: ([\d\.,]+)\/([\d\.,]+)$/, '生命值: $1\/$2'],
    [/^Defense: ([\d\.,]+)$/, '防御: $1'],
    [/^Rare: ([\d\.,]+)\%$/, '稀有: $1\%'],
    [/^Uncommon: ([\d\.,]+)\%$/, '罕见: $1\%'],
    [/^Common: ([\d\.,]+)\%$/, '普通: $1\%'],
    [/^Legendary: ([\d\.,]+)\%$/, '传说: $1\%'],
    [/^Epic: ([\d\.,]+)\%$/, '史诗: $1\%'],
    [/^Attack: ([\d\.,]+)$/, '攻击: $1'],
    [/^GS: ([\d\.,]+)$/, '装备评分(GS): $1'],
    [/^LVL ([\d\.,]+)$/, '等级 $1'],
    [/^Slot ([\d\.,]+)$/, '槽位 $1'],
    [/^Found Level ([\d\.,]+) Vault Key$/, '发现 等级 $1 金库钥匙'],
    [/^Level ([\d\.,]+) Vault Key$/, '等级 $1 金库钥匙'],
    [/^Floor ([\d\.,]+)$/, '层数 $1'],
    [/^Opened Level ([\d\.,]+) Chest → Lvl ([\d\.,]+)$/, '已打开 等级 $1 宝箱 → 等级 $2'],
    [/^Opened Level ([\d\.,]+) ✨ Mythic Chest → Lvl ([\d\.,]+)$/, '已打开 等级 $1 ✨ 神话宝箱 → 等级 $2'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Lvl ([\d\.,]+) Common$/, '等级 $1 普通'],
    [/^Lvl ([\d\.,]+) Rare$/, '等级 $1 稀有'],
    [/^Lvl ([\d\.,]+) \(\+([\d\.,]+)\)$/, '等级 $1 (+$2)'],
    [/^Respawn \(([\d\.,]+)s\)$/, '重生 ($1 秒)'],
    [/^Floor ([\d\.,]+) Failed$/, '层 $1 失败'],
    [/^Floor ([\d\.,]+) Complete$/, '层 $1 完成'],
    [/^Floor ([\d\.,]+) complete$/, '层 $1 完成'],
    [/^Continue to Floor ([\d\.,]+) \(([\d\.,]+)s\)$/, '继续到 层 $1 ($2秒)'],
    [/^💎 Gear Score: ([\d\.,]+) \- Best floor reached: ([\d\.,]+)$/, '💎 装备评分: $1 - 达到的最佳层数: $2'],
    [/^Score submitted! Floor ([\d\.,]+), Gear Score ([\d\.,]+)$/, '分数已提交! 层数 $1, 装备评分 $2'],
    [/^💰 ([\d\.,]+)g$/, '💰 $1 金币'],
    [/^Bonus Loot \(([\d\.,]+) Items\)$/, '奖励战利品 ($1 物品)'],
    [/^Auto-selling items below level ([\d\.,]+)$/, '自动出售物品在等级低于 $1'],
    [/^Cooldown: ([\d\.,]+)s \| Mana Cost:$/, '冷却: $1秒 | 法力成本:'],
    [/^🔒 Vault - Lvl ([\d\.,]+) Key$/, '🔒 金库 - 等级 $1 钥匙'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Equipped Lvl ([\d\.,]+)$/, '已装备 等级 $1'],
    [/^reached level ([\d\.,]+)! \(\+([\d\.,]+) skill point\)$/, '达到等级 $1! (+$2 技能点)'],
    [/^heals Archer for ([\d\.,]+)$/, '治疗了 射手 $1'],
    [/^heals Tank for ([\d\.,]+)$/, '治疗了 坦克 $1'],
    [/^heals Healer for ([\d\.,]+)$/, '治疗了 自己 $1'],
    [/^heals Rogue for ([\d\.,]+)$/, '治疗了 刺客 $1'],
    [/^heals Paladin for ([\d\.,]+)$/, '治疗了 圣骑士 $1'],
    [/^heals Mage for ([\d\.,]+)$/, '治疗了 法师 $1'],
    [/^fires Multi-Shot at ([\d\.,]+) enemies$/, '向 $1 个敌人发射了 多重射击'],
    [/^equips Lvl ([\d\.,]+)$/, '装备了 等级 $1'],
    [/^Fallen Scout drops Lvl ([\d\.,]+)$/, '陨落的侦察兵 掉落了 等级 $1'],
    [/^Moss Boar drops Lvl ([\d\.,]+)$/, '苔藓野猪 掉落了 等级 $1'],
    [/^Tunnel Rat drops Lvl ([\d\.,]+)$/, '隧道老鼠 掉落了 等级 $1'],
    [/^Smelter Imp drops Lvl ([\d\.,]+)$/, '熔炼小恶魔 掉落了 等级 $1'],
    [/^Ember Sprite drops Lvl ([\d\.,]+)$/, '灰烬精灵 掉落了 等级 $1'],
    [/^Colossus Of Iron drops Lvl ([\d\.,]+)$/, '钢铁巨像 掉落了 等级 $1'],
    [/^Red Stag drops Lvl ([\d\.,]+)$/, '红鹿 掉落了 等级 $1'],
    [/^Autumn Wisp drops Lvl ([\d\.,]+)$/, '秋日小精灵 掉落了 等级 $1'],
    [/^Bandit Cutthroat drops Lvl ([\d\.,]+)$/, '强盗杀手 掉落了 等级 $1'],
    [/^Briar Spider drops Lvl ([\d\.,]+)$/, '荆棘蜘蛛 掉落了 等级 $1'],
    [/^Anvil Guard drops Lvl ([\d\.,]+)$/, '铁砧守卫 掉落了 等级 $1'],
    [/^Hollow Cultist drops Lvl ([\d\.,]+)$/, '熔融史莱姆 掉落了 等级 $1'],
    [/^Abyssal Leech drops Lvl ([\d\.,]+)$/, '深渊吸血怪 掉落了 等级 $1'],
    [/^Night Stalker drops Lvl ([\d\.,]+)$/, '夜行者 掉落了 等级 $1'],
    [/^Oreback Beetle drops Lvl ([\d\.,]+)$/, '牛背甲虫 掉落了 等级 $1'],
    [/^Forest Wolf drops Lvl ([\d\.,]+)$/, '森林狼 掉落了 等级 $1'],
    [/^Colossus Of Iron drops Lvl ([\d\.,]+)$/, '钢铁巨像 掉落了 等级 $1'],
    [/^Night Herald drops Lvl ([\d\.,]+)$/, '暗夜使者 掉落了 等级 $1'],
    [/^Shade drops Lvl ([\d\.,]+)$/, '阴影 掉落了 等级 $1'],
    [/^Maw Of Deep drops Lvl ([\d\.,]+)$/, '深渊之肚 掉落了 等级 $1'],
    [/^Gloomling drops Lvl ([\d\.,]+)$/, '暗影幼体 掉落了 等级 $1'],
    [/^Molten Slime drops Lvl ([\d\.,]+)$/, '熔融史莱姆 掉落了 等级 $1'],
    [/^Void Mite drops Lvl ([\d\.,]+)$/, '虚空螨 掉落了 等级 $1'],
    [/^Elder Treant drops Lvl ([\d\.,]+)$/, '老树精 掉落了 等级 $1'],
    [/^Forge Golem drops Lvl ([\d\.,]+)$/, '锻造魔像 掉落了 等级 $1'],
    [/^Foundry Master drops Lvl ([\d\.,]+)$/, '铸造大师 掉落了 等级 $1'],
    [/^Treasure Guardian drops Lvl ([\d\.,]+)$/, '宝藏守护者 掉落了 等级 $1'],
    [/^Umbral Depths \- Floor ([\d\.,]+)$/, '阴暗的深处 - 层数 $1'],
    [/^Everfall \- Floor ([\d\.,]+)$/, '永恒陨落 - 层数 $1'],
    [/^Stoneforge \- Floor ([\d\.,]+)$/, '石炉 - 层数 $1'],
    [/^Ring ([\d\.,]+):$/, '戒指 $1:'],
    [/^Start: ([\d\.,]+) \| Best: ([\d\.,]+)$/, '开始: $1 | 最佳: $2'],
    [/^Slot ([\d\.,]+) \- Front$/, '槽位 $1 - 前'],
    [/^Slot ([\d\.,]+) \- Back$/, '槽位 $1 - 后'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);
